### ISSUE TITLE
Reasignación de corrección

### ISSUE THREAD

**Issue by diegosanchez** [fiuba/alfred#111]
Cuando quiero re-asignar una corrección aparece una lista de docentes especificando el nombre.  Como hay varios *Diegos* no se puede saber a quién estoy re-asignando.  La lista de docentes debería ser Nombre y Apellido.

**Comment by nicopaez** [comment]
Ya lo estan trabajando alumnos de UNQ.

**Comment by nicopaez** [comment]
Ya está implementado.

**Comment by diegosanchez** [comment]
goood

On 17 August 2015 at 00:45, Nicolas Paez <notifications@github.com> wrote:

> Ya está implementado.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fiuba/alfred/issues/111#issuecomment-131672010>.
>



-- 
Saludos
DiegoS

------

Diego Sanchez
[image: http://]about.me/sanchez.diego
<http://about.me/sanchez.diego?promo=email_sig>
